<!-- README.md is generated from README.Rmd. Please edit that file -->

# TATE: Text Analysis for English

The goal of TATE is to make text analysis a bit easier. TATE is composed of a few functions for text quantification. It uses external norms of valence, arousal, dominance, concreteness, humor, extrimiety and emotionality. The function take strings as input, executes lemmatization of the string and returns a value.

## Examples

```{r example}
library(TATE)
NoVAD("I'm sad")
concretness("I'm sad")
funny("I'm sad")
EvLex("I'm sad")
```

##References

Brysbaert, M., Warriner, A. B., & Kuperman, V. (2014). Concreteness ratings for 40 thousand generally known English word lemmas. Behavior research methods, 46(3), 904-911.

Engelthaler, T., & Hills, T. T. (2018). Humor norms for 4,997 English words. Behavior research methods, 50(3), 1116-1124.

Rocklage, M. D., & Fazio, R. H. (2015). The Evaluative Lexicon: Adjective use as a means of assessing and distinguishing attitude valence, extremity, and emotionality. Journal of Experimental Social Psychology, 56, 214-227.

Warriner, A. B., Kuperman, V., & Brysbaert, M. (2013). Norms of valence, arousal, and dominance for 13,915 English lemmas. Behavior research methods, 45(4), 1191-1207.
